
# 1. Name the service (This is how other services will search for it)
spring.application.name=market-data-service

# 2. Assign a port. (8081 is standard for a second service. 8761 is already taken by the server)
server.port=8081

# 3. Point it to the Eureka Server's default URL
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true