spring.application.name=demoEurekaServices

# Standard port for Eureka Servers
server.port=8761

# Tell this instance not to register with a registry (since it IS the registry)
eureka.client.register-with-eureka=false

# Tell it not to fetch the registry information locally
eureka.client.fetch-registry=false

# Disable self-preservation for local development
eureka.server.enable-self-preservation=false