spring.application.name=demoValidation

spring.datasource.url=jdbc:mysql://localhost:3306/cricket_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

cricapi.key=eb416aa1-71ce-45a9-98c0-75fed739cd45